POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "nguyenthao",
    "email": "thanhhoang090497@gmail.com",
    "password": "nguyenthao123"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "thanhhoang090497@gmail.com",
    "password": "nguyenthao123"
}

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "phucthuhigh",
    "email": "phucthuhigh123@gmail.com",
    "password": "phuc1701_"
}